Settings:
  updater: true
  bstats: true

#Database types: local, mysql
Database:
  type: local
  table-name: integrity_economy
  mysql:
    host: localhost
    port: 3306
    database: economy
    username: root
    password: password
    useSSL: false

Economy:
  formatted: "{rounded-money} {currency}"
  currencyPlural: "Moneys"
  currencySingolar: "Money"
  first-join-money: 200
  save-minutes: 30

#####################################
#        INTEGRITY - PREFIXES       #
# Commons:                          #
#  - {prefix} > Display prefix      #
#####################################
Messages:
  prefix: "<color:#8291ff><b>IE</b></color>" # NO COMMONS
  player-offline: "{prefix} <gradient:#c2ccff:#d6e6ff>The player is offline!</gradient>"
  no-permission: "{prefix} <gradient:#c2ccff:#d6e6ff>You don't have the permission!</gradient>"
  your-balance: "{prefix} <gradient:#c2ccff:#d6e6ff>You have {balance}</gradient>" # COMMONS - {balance}
  other-balance: "{prefix} <gradient:#c2ccff:#d6e6ff>{player} have {balance}</gradient>" # COMMONS - {player} - {balance}
  usage-balance: "{prefix} <gradient:#c2ccff:#d6e6ff>Usage: /balance [player]</gradient>"
  eco-reset: "{prefix} <gradient:#c2ccff:#d6e6ff>{player}'s balance has been resetted</gradient>" # COMMONS - {player}
  not-enough: "{prefix} <gradient:#c2ccff:#d6e6ff>{player} does not have money!</gradient>" # COMMONS - {player}
  eco-give: "{prefix} <gradient:#c2ccff:#d6e6ff>You gave {player} {amount}!</gradient>" # COMMONS - {player} - {amount}
  eco-set: "{prefix} <gradient:#c2ccff:#d6e6ff>You set {amount} for {player}!</gradient>" # COMMONS - {player} - {amount}
  eco-remove: "{prefix} <gradient:#c2ccff:#d6e6ff>You took {amount} from {player}!</gradient>" # COMMONS - {player} - {amount}
  usage-eco: "{prefix} <gradient:#c2ccff:#d6e6ff>Usage: /eco <give/remove/reset> <player> [amount]</gradient>"
  player-does-not-exist: "{prefix} <gradient:#c2ccff:#d6e6ff>This player does not exist!</gradient>"
  invalid-number: "{prefix} <gradient:#c2ccff:#d6e6ff>Invalid number formatting!</gradient>"
  pay-self: "{prefix} <gradient:#c2ccff:#d6e6ff>You paid {player} {amount}!</gradient>" # COMMONS - {player} - {amount}
  pay-other: "{prefix} <gradient:#c2ccff:#d6e6ff>You received {amount} from {player}!</gradient>" # COMMONS - {player} - {amount}
  pay-try-self: "{prefix} <gradient:#c2ccff:#d6e6ff>You cannot pay yourself!</gradient>"
